### ISSUE TITLE
node_modules\@xylink\xy-electron-sdk\build\Release\xy-electron-sdk.node is not a valid Win32 

### ISSUE THREAD

**Issue by sohoorc** [xylink-com/xylink-electron-vue-demo#2] opened 2020-08-28 08:59 UTC
执行 yarn dev

electron控制台提示 node_modules\@xylink\xy-electron-sdk\build\Release\xy-electron-sdk.node is not a valid Win32

**Comment by luojinghui** [comment] 2020-08-28 09:39
Duplicate of https://github.com/xylink-com/xylink-electron-vue-demo/issues/1

请在另一个issue上尝试解决。

**Closed as completed** 2020-08-28 09:38 UTC
